### ISSUE TITLE
Revisar pull request del diagrama grupo 3

### ISSUE THREAD

**Issue by oscarescuderoarnanz** [DanielRiveraPaniagua/ProyectoFinal_ISI#10]
Hemos revisado el diagrama subido y no nos terminar de cuadrar, por lo que hemos planteado una solución alternativa para el diagrama.

**Comment by DanielRiveraPaniagua** [comment]
¿Podríais detallar por qué no os cuadraba?

Por otra parte la tabla de clientes creo que podríamos dejarla para más tarde ya que queremos centrarnos un poco sobre las funcionalidades básicas, no obstante no me parece mal que la hayáis contemplado.

Responded si queréis en el issue #11 donde dejo más información sobre mi opinión, gracias.

**Comment by DanielRiveraPaniagua** [comment]
Pull Request aceptado y discusión movida a #11
