### ISSUE TITLE
Fusión de pull request y finalización del proyecto

### ISSUE THREAD

**Issue by dpoloa** [DanielRiveraPaniagua/ProyectoFinal_ISI#104]
Abro esta issue por la necesidad de aclarar que, a menos de 2 días para la entrega del proyecto, nos encontramos con 5 pull request abiertos, siendo algunos funcionalidades menores y otros con mucho mayor peso que deberían estar sí o sí en el proyecto.

El problema no es la presencia de tantos pull request, sino la necesidad de **arreglar** los posibles conflictos que se den cuando empecemos a fusionarlos. Además, una vez fusionados, deberíamos comprobar que funcionan todas las funcionalidades que hemos implementado, lo cual puede llevar o dos minutos u horas si vemos que no funciona algo. En mi caso personal, no me gustaría estar "trabajando a destajo" el domingo para arreglar posibles fallos en la integración del proyecto.

Si se necesita ayuda con alguna implementación, se puede avisar por el grupo. Hay grupos con funcionalidades muy encarriladas (me incluyo) que podemos apoyar en otros campos del proyecto.

**Comment by DanielRiveraPaniagua** [comment]
Razón de esto: En general se está empezando a trabajando en el proyecto muy tarde.

Opciones: dejar de añadir funcionalidades pequeñas e innecesarias y dejar a los otros grupos con funcionalidades grandes trabajar además de por dejar de tener que resolver constantes conflictos, por dejar de necesitar su ayuda para implementar cosas.

No, no deberíamos tener que probar si funciona o no las funcionalidades porque se supone que nadie es tan inconsciente de meter una funcionalidad al proyecto a medio hacer. Aun así habrá que probarlas.

Si no puedes dedicarle el domingo al proyecto no pasa nada, más cuando vuestra funcionalidad está bien terminada y funciona perfectamente, habéis hecho un buen trabajo y con tiempo. Entiendo las cosas que dices y comparto tu opinión, pero yo no tengo ningún problema en dedicarle todo el tiempo necesario, ya estoy demasiado metido en ello como para dejarlo ahora XD.

**Comment by DanielRiveraPaniagua** [comment]
Proyecto listo para últimos commits
