### ISSUE TITLE
Revisión de el diagrama

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#11]
Tras revisar ambos diagramas (el propuesto por el grupo 3 y el grupo 4)  saco las siguientes ideas:

En el diagrama del grupo 3 faltan relaciones del tipo, todos los actores han trabajado en alguna película, y todas las películas son dirigidas por, al menos, un director, cosas así.

Por otra parte, guionistas, actores y directores tienen básicamente los mismos campos así que podrían contenerse en una relación del tipo es un (esto va para ambos grupos y es más que nada por tener un diagrama ordenado ya que a la hora de hacer las tablas no se va a ver reflejado).

No me decanto del todo ni por la opción del grupo 4 de meter en única relación todos los actores, directores y guionistas que trabajaron en una película o separarlos en varias relaciones como el grupo 3. Me ayudaría que explicaseis las razones por las que lo veis así.

Finalmente en la información recogida por el grupo 1 y 2 no se ve en ningún momento las productoras, ¿vamos a poder trabajar con esa información?

Dejad vuestras respuestas al diagrama a continuación, por favor, para mantener una discusión continuada.

**Comment by DanielRiveraPaniagua** [comment]
Finalmente creo que me convence más la forma del grupo 3 de tener las relaciones a actores, directores y guionistas separados, puesto que así, no solo va a estar más ordenado, sino que también a la hora de trabajar con cada una de las tablas va a ser más sencillo.

**Comment by angeisa97** [comment]
No encontramos ninguna información sobre productoras en las bases de datos de IMDb.
Yo también creo que la forma mas sencilla es separar las relaciones en el diagrama

**Comment by Noozh** [comment]
Varios apuntes sobre lo que he podido ver de ambos diagramas:

- En los dos sobraria la entidad productores de acuerdo con la informacion sobre los datos que tenemos disponibles que han recogido los grupos 1 y 2.

- Segun he visto la puntuacion (rating) esta asociada a la pelicula; ninguno de los dos diagramas recoge el rating como un atributo de la entidad pelicula.

**Sobre el diagrama del grupo3:**
- La entidad peliculas no tiene ningun atributo y deberia tener al menos id_pelicula , nombre, fecha_de_publicacion y rating.

- Me parece que no vamos a tener informacion de clientes tal y como la teneis reflejada en vuestra entidad clientes, por lo que en mi opinion descartaria esa entidad al menos en ese formato.

- Faltan restricciones de clave tales como una pelicula pertenece al menos a un genero o una pelicula esta dirigida al menos por un director.

**Sobre el diagrama del grupo4:**

- No entiendo el proposito del atributo Nickname en la entidad actores.

- Habria que agregar un atributo rating a la entidad pelicula.

- En mi opinion meteria alguna restriccion de clave mas tal como una pelicula es dirigida al menos por un director o en una pelicula trabaja al menos un guionista.


Dicho esto el diagrama del grupo 4 me parece mas completo que el del grupo 3

**Comment by victorbrobles** [comment]
Yo veo bien lo de la relación es-un entre directores y guionistas, pero creo que es necesario tener relacionadas las cuatro entidades con una sola relación.

Luego también habría que modificar un poco el tema de los atributos y de las restricciones.

**Comment by oscarescuderoarnanz** [comment]
La idea básica de porque no plantee la relación es-un en el diagrama3 es por facilitar la elaboración de la base de datos y el trabajo con esta, pues creo que es mas intuitivo tener las relaciones-entidades separadas, que relacionadas las cuatro entidades con una sola relación.
Por lo demás estoy de acuerdo con quitar las entidades Clientes y Productores y sus respectivas relaciones, y añadir los atributos correspondientes a Películas.

**Comment by DanielRiveraPaniagua** [comment]
Creo que éste diagrama refleja todo lo que hemos ido diciendo.

Adicionalmente he añadido la entidad calificación que debería estar separada puesto que no es una cualidad de película sino un atributo que se le añade a ella.

Creo que los actores, directores y guionistas deberían estar separados por el hecho de que no dependen unos de otros, dependen de la película en la que han trabajado nada más (cambiar por ejemplo el nombre de el id de un director nos costaría cambiarlo en cada fila que habría que generar para cada actor). Por otra parte esto acabará generándonos muchas más filas, que es un problema que tenemos que tener en cuenta.

Por otra parte, he quitado las relaciones de integridad de clave porque desconozco si en la información que nos han pasado puede haber más de un director, guionista o calificación para una misma película

La elaboración con o sin la entidad es-un es la misma ya que podemos no tener en ningún momento una tabla personas, pero así indicamos la razón de que todas tengan los mismos atributos básicos.

![Diagrama g5](https://user-images.githubusercontent.com/57093249/69918982-58670900-1478-11ea-8486-4edb793be6df.jpg)

**Comment by DanielRiveraPaniagua** [comment]
Diagrama y especificaciones comentadas en clase subidas a la wiki
