### ISSUE TITLE
Calificación por edades

### ISSUE THREAD

**Issue by dpoloa** [DanielRiveraPaniagua/ProyectoFinal_ISI#16]
Para probar el diagrama E/R usaremos los datos dados por Pedro, pero a la hora de obtener los datos de iMDB no aparece en el dataset ninguna información relacionada con la calificación por edades.

Para más adelante, me gustaría saber si usaremos los datos que vienen en las páginas web de las películas, de qué país escogemos su calificación, etc.

**Comment by DanielRiveraPaniagua** [comment]
Podemos seguir investigando si conseguimos ese tipo de información de algún data set de otra pagina (a lo mejor de la entidad que realice estas calificaciones)

Si no, me parece bien la solución de coger la calificación de la web.

**Comment by DanielRiveraPaniagua** [comment]
¿Dejamos el tema resuelto como, "de momento trabajar solamente con los datos de Pedro"?

**Comment by oscarescuderoarnanz** [comment]
En IMDb , en la tabla title.basics.tsv aparece el campo isAdult, lo cual nos permite calificar si es de adultos o no, esto sería una buena opción para continuar de momento, calificar las películas en adultos o no.
![title basics tsv](https://user-images.githubusercontent.com/47352810/70328779-24a22f80-183a-11ea-8c08-b65d780497c2.png)

**Comment by DanielRiveraPaniagua** [comment]
Podemos unirlo a la información que ya tenemos, poniendo que si no tienen calificación ya asignada, dividir si son adultos o no, por ejemplo, ¿qué os parece?

**Comment by dpoloa** [comment]
El pull request #38 contiene la tabla de la entidad Calificaciones en función de si la película es para adultos o no. Podemos trabajar con ello por ahora y modificarla más tarde.

**Comment by DanielRiveraPaniagua** [comment]
Separamos si son de adultos o no
