### ISSUE TITLE
Utilidad de la información de idiomas de las películas

### ISSUE THREAD

**Issue by jaime0907** [DanielRiveraPaniagua/ProyectoFinal_ISI#17]
De IMDB hemos sacado un archivo dónde vienen los títulos de las películas en distintos idiomas (title.akas). No hay ninguna funcionalidad que use esta información. Pienso que podríamos añadir una funcionalidad que consista en que el cliente nos de su idioma preferido en la petición de los datos, y así podamos devolverle el nombre de la/las películas en el idioma que especifique, y si el nombre de la película no está en ese idioma, devolverle el idioma por defecto (en el mismo archivo title.akas viene cuál de todos los títulos es el que usa IMDB por defecto)
Otra opción igual de válida sería ignorar estos datos.
¿Qué hacemos?

**Comment by Noozh** [comment]
Me parece buena idea que se incluya como nueva funcionalidad, si los demas estais de acuerdo agregadlo a la documentación de funcionalidades.

**Comment by DanielRiveraPaniagua** [comment]
Me parece interesante, si queréis añadidlo en la wiki en la sección de las funcionalidades.

**Comment by dpoloa** [comment]
Me parece una muy buena idea.

**Comment by DanielRiveraPaniagua** [comment]
Añadida funcionalidad a la wiki
