### ISSUE TITLE
Nombre del personaje de un actor

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#19]
Según he estado viendo, en los datos de los que disponemos en title.principals para los actores principales de ciertas películas tenemos el nombre de los personajes que interpretan, podría ser útil dar esa información para algunas queris.

¿Qué os parece?

**Comment by JavierBravoDonaire** [comment]
Me parece buena idea pero tenemos que pensar una funcionalidad basada en eso y la dejaría en segundo plano mientras se realizan las demás.

**Comment by DanielRiveraPaniagua** [comment]
Yo creo que una funcionalidad para esto ya tenemos, cuando sacamos la información de la película, en la que tendrán que venir los actores, podemos añadir además su personaje.

**Comment by JavierBravoDonaire** [comment]
Entonces lo veo perfecto :+1: .

**Comment by Noozh** [comment]
Siempre es bueno tener mas información, lo que no veo claro es como vamos a guardar esta información en base de datos.

**Comment by DanielRiveraPaniagua** [comment]
Se podría guardar como atributo de la relación trabajan, entre actores y películas

**Comment by DanielRiveraPaniagua** [comment]
Irrelevante actualmente
