### ISSUE TITLE
Documentacion del codigo Java

### ISSUE THREAD

**Issue by Noozh** [DanielRiveraPaniagua/ProyectoFinal_ISI#31]
He estado probando la generacion de documentacion de las clases java a partir de las anotaciones javadoc. El resultado es muy bueno y es extremadamente sencilla de generar, el unico problema que tiene es que al generarse la documentacion en html se requiere alojamiento.

Segun he podido ver github ofrece la posibilidad de alojar documentos html (como estos javadocs) en una pagina de github. **Me gustaria que compartieseis vuestra opinion sobre el hecho de implantar este sistema de paginas de github para alojar documentacion relativa al codigo de java**.
A continuacion os dejo un enlace con la documentacion de como habilitar las paginas en github (solo puede hacerlo el propietario del repositorio) :

`https://pages.github.com/` 

Tambien os adjunto la pagina de un proyecto que he encontrado que utiliza github para alojar los javadocs:

`http://ebourg.github.io/jsign/apidocs/`

**Comment by DanielRiveraPaniagua** [comment]
Me parece interesante, pero puede que sea añadir una capa más de complejidad al proyecto que tampoco aporte demasiado. No obstante, no se como sé manejar github pages y puede ser incluso más fácil de lo que parece configurarlo para los javadocs. Podríamos probarlo y ver que tal.

Puesto que solo puede dar permisos el dueño del repo, me pongo en contacto contigo y, por probarlo y mera curiosidad, lo activamos. Luego ya veremos si es bueno para el proyecto :)

**Comment by felipecordente** [comment]
Perdonar, pero no entiendo muy bien para que podria ser util la generación de documentación ,si me podeis dar una pequeña explicación y mostrarme un ejemplo de la misma lo agradeceria.
Muchas gracias de antemano.

**Comment by Noozh** [comment]
@felipecordente A lo que me refiero es a generar documentacion de los metodos de las clases de java que vayamos haciendo de manera automatica con un resultado como el que se tiene en esta url:

`http://ebourg.github.io/jsign/apidocs/`

**Comment by dpoloa** [comment]
Puede ser una buena implementación, aunque la considero bastante prescindible. No obstante, si vemos que hay tiempo suficiente y se puede implementar de forma sencilla, se puede realizar.

**Comment by Noozh** [comment]
Cierro issue ya que a estas alturas ya no va a implementarse
