### ISSUE TITLE
Propuesta API de conexion a base de datos desde java

### ISSUE THREAD

**Issue by Noozh** [DanielRiveraPaniagua/ProyectoFinal_ISI#32]
He estado dandole unas vueltas a una primera version de la API jdbc para Java, os adjunto a continuacion un borrador del diagrama de interfaces que se me ha ocurrido:

![API_DAO](https://user-images.githubusercontent.com/44481102/70227957-cdc22a80-1753-11ea-8f0f-87069ebeed4f.jpeg)

La idea es que todas las interfaces que se asocian con la tabla de cada entidad van a heredar de una interfaz generica **que contiene operaciones comunes a todas las tablas**. A mi se me han ocurrido como operaciones comunes conectarse a la base de datos, seleccionar todos los elementos de una tabla, seleccionar un elemento por id de una tabla, borrar un elemento por id de una tabla y cerrar la conexion con la base de datos.

Las interfaces asoaciadas a la tabla de una entidad **deberian implementar los metodos especificos para la extranccion de los datos de esa tabla**. Por ejemplo la entidad pelicula tiene atributo duracion, por lo que un metodo especifico para esta tabla puede ser coger todas las peliculas con duracion menor a 120 minutos.

En el caso de las entidades que heredan de la entidad persona (cuya tabla no existe como tal en nuestra base de datos)  creo que seria buena idea definir una interfaz persona que **englobe todos los metodos comunes a las entidades que heredan de persona** (que por el momento son todos), e interfaces para cada entidad que hereda de persona en las cuales **se podrian definir metodos especificos para cada una** si se agregara en un futuro algun atributo mas a estas entidades.

Me gustaria que debatiesemos esta propuesta.

**Comment by DanielRiveraPaniagua** [comment]
Me parece una buena organización de las interfaces y buenos métodos generales. Quizá el método de seleccionar todo es el le veo menos uso tal y como tenemos planteadas las queris. 

¿Las relaciones dónde entrarían?

**Comment by Noozh** [comment]
Tecnicamente creo que no es necesaria la creacion de interfaces para tablas relacionales por como se concibe el patron DAO; voy a intentar explicarme.

Basicamente cuando se usa un patron DAO lo que se pretende es tener una **capa de acceso a los datos** que nos va a abstraer de como se obtienen esos datos. En nuestro caso los datos que vamos a extraer siempre van a ser Entidades, esto es peliculas, actores .... y por ello estas entidades tienen un objeto DAO **que sirve para recoger los resultados de las consultas en java**.

Las interfacesDAO son las que definen las operaciones que queremos realizar sobre una tabla entidad **y las tablas relacionales asociadas a esta entidad**. Por tanto en InterfacePeliculaDAO se puede definir la operacion traerPeliculaPorNombre (que solo implica la tabla pelicula)  pero tambien podria definirse ahi traerPelisTerror( que implica peliculas , pertenece e incluso la propia tabla generos).

**Comment by felipecordente** [comment]
Yo lo veo bastante bien, además es simple y bastante intuitivo.

**Comment by JavierBravoDonaire** [comment]
Coincido con felipe.

**Comment by DanielRiveraPaniagua** [comment]
Api establecida
