### ISSUE TITLE
Nueva funcionalidad y asignación de funcionalidades al grupo 1

### ISSUE THREAD

**Issue by dpoloa** [DanielRiveraPaniagua/ProyectoFinal_ISI#39]
Al grupo 1 se nos ha ocurrido una nueva funcionalidad: recomendar películas según la edad del usuario, como si se tratara de un Netflix infantil o un Youtube Kids. Es muy sencillo de implementar (por ahora es solo obtener aquellas películas de iMDB con el distintivo de no adulto).

Además, añado que nos gustaría, en el caso de que esta funcionalidad se añadiera, asignárnosla como trabajo, así como la funcionalidad del ranking de películas.

Dejo constancia en la issue y en la wiki del proyecto.

**Comment by DanielRiveraPaniagua** [comment]
Okey, me parece correcto. Visto el issue

**Comment by DanielRiveraPaniagua** [comment]
No veo la adición en la wiki

**Comment by angeisa97** [comment]
Añadido a la wiki en el apartado funcionalidades

**Comment by dpoloa** [comment]
Perdón, añadí las funcionalidades del grupo 1 al proyecto, no a la wiki. Esperaba confirmación de los demás para añadirla como una nueva funcionalidad, aunque @angeisa97 ya lo ha añadido.

**Comment by DanielRiveraPaniagua** [comment]
Pues cerrado queda el issue
