### ISSUE TITLE
Cantidad de datos de entrada desborda enormemente tamaño de la base de datos

### ISSUE THREAD

**Issue by Noozh** [DanielRiveraPaniagua/ProyectoFinal_ISI#4]
He estado haciendo una limpieza de los datos que nos ha proporcionado el cliente, eliminando peliculas repetidas entre ficheros y formateando los dato y he obserbado que en los datos hay 290617 peliculas distintas.

Como el tamaño maximo de tabla que permite heroku es de 10000 tendremos que elegir algun criterio para elegir 10000 peliculas de entre el total de peliculas.

Imagino que vamos a tener este problema con el resto de los datos.

**Comment by DanielRiveraPaniagua** [comment]
¿Pero son 10000 lineas en total entre todas las tablas o por tabla?

**Comment by Noozh** [comment]
Segun la documentación son 10000 lineas en total : `https://devcenter.heroku.com/changelog-items/96`

**Comment by DanielRiveraPaniagua** [comment]
Pues habrá que limitar el número de todo entonces para poder adaptarnos a esas restricciones. Supongo que hay más actores que películas, pocos directores, y guionistas... unos cuantos?
Hay que mirar que proporción ponemos y como lo decidimos.

(A lo mejor coger las 500 primeras películas, sus actores y directores, algo así)

**Comment by angeisa97** [comment]
hemos visto el mismo problema en el resto de ficheros de datos. 

Podriamos coger directamente las 500 primeras peliculas, ordenadas por id_pelicula

**Comment by prodriguezmartinez** [comment]
Estoy de acuerdo con angeisa97

**Comment by felipecordente** [comment]
Yo haría algo como lo que dice Daniel Rivera, coger un número x de películas y sus relaciones con el resto de entidades.

**Comment by angeisa97** [comment]
Vuelvo a comentar en esta issue para dejar reflejado lo que se habló por WhatsApp. Una vez obtenidas las películas que coinciden en ambos ficheros, habría que tener un criterio de selección.
Se propuso elegir las películas con mayor ranking. Yo mantendría escoger las 500 primeras películas de mayor ranking solamente y luego sus relaciones con las demás entidades.

**Comment by DanielRiveraPaniagua** [comment]
El problema de elegir actores o películas al azar es que pueden quedar nodos desconectados completamente en los grafos, por ejemplo, así que tampoco es un trabajo que podamos realizar a la ligera. Tendremos que elegir aquellas películas que nos permitan explotar todas nuestras funcionalidades también. Pero es cierto que hay que decidir que método vamos a usar.

**Comment by angeisa97** [comment]
Las peliculas con mejor rating seguramente sean las peliculas más famosas. De igual forma, los actores mas famosos son los que actuan en estas peliculas asi que yo creo que de esta forma si podriamos usar nuestras funcionalidades

**Comment by DanielRiveraPaniagua** [comment]
No te digo que no, simplemente añadía que hay que tener en cuenta que hay que tener un poco cuidado. Que lo estuvimos comentando unos compañeros y yo el otro día, para dejarlo reflejado también.

**Comment by felipecordente** [comment]
Creo que de momento podemos probar con las 500 más valoradas, y luego si se nos ocurre otra forma de hacer selección, simplemente seria modificarlo, tampoco seria mucho problema.

**Comment by DanielRiveraPaniagua** [comment]
Se decide finalmente trabajar con las 500 películas más famosas y todas las demás tablas dependen de éstas.
