### ISSUE TITLE
Información sobre despliegue auxiliar

### ISSUE THREAD

**Issue by joserequena1998** [DanielRiveraPaniagua/ProyectoFinal_ISI#40]
Me gustaría saber como realizar un despliegue auxiliar(travis-heroku) sobre nuestro repositorio, para no pisar el despliegue del repositorio principal.
He seguido estos pasos.:
- Me creo un repositorio nuevo y le clono la información del repositorio principal.
- Me creo el proyecto Maven en eclipse para importarme el repositorio en el área de trabajo.
- Me modifico el .travis.yml, poniendo el nombre del repositorio y mi API key.
- Me importo el proyecto de GitHub en travis.
- Ejecuto el comando heroku create NOMBRE_REPOSITORIO
- Me creo una nueva API key y actualizo pom.xml poniendo mi appname.
- Actualizo mi repositorio.

**Comment by DanielRiveraPaniagua** [comment]
Eso es. Recordad luego tener cuidado en el pull request de no llevaros el .travis.yml nuevo

**Comment by DanielRiveraPaniagua** [comment]
¿Para qué querrías trabajar con un despliegue en heroku? Me refiero: una vez el despliegue ya está hecho podrías trabajar con los métodos ejecutándolos localmente y debería seguir funcionando, así no tienes que cambiar la clave, etc. 

Si quisieras heroku aun así para ver el despliegue funcionando online, creo que sí estás haciendo lo correcto. El cuidado que tienes que tener es que luego al subir cosas aquí (hacer el pull request) los nombres y claves del pom.xml y de .travis.yml no cambien. El pom si quisieras añadir nuevas dependencias si puedes tocarlo, pero no el nombre del fichero de despliegue.

No se si entiendo bien qué es lo que quieres conseguir. Si lo que he contestado no se ajusta a tu pregunta discúlpame, intenta volverlo a preguntar por favor.

**Comment by DanielRiveraPaniagua** [comment]
Si el tema está resuelto, por favor, cerrarlo.
