### ISSUE TITLE
Creación de tablas en jdbc

### ISSUE THREAD

**Issue by JavierBravoDonaire** [DanielRiveraPaniagua/ProyectoFinal_ISI#43]
He estado leyendo el código en el que se crean las tablas con jdbc y me ha surgido una duda. Estoy montando una página de la wiki con una API rest provisional (crecerá con las funcionalidades).
El caso es que los programas:
     Actores.java
     Peliculas.java 
Tienen ambos un método en el que se realiza una petición get en la que se devuelve un formulario que acepta un fichero .txt del que se va a leer y realizar las tablas. Una vez añadido el fichero al formulario se realiza una petición post, la duda que tengo es que en ambos programas la url que se usa en ese post es la misma (/upload) ¿es esto correcto?¿Como se diferencia entonces si es una película o es un actor?
Además el get de los formularios (/upload_films) es también igual en ambos, ¿Cómo se diferencia entonces si es el fichero de actores o es el de pelis el que se ha recibido?
Estoy realizando la wiki teniendo en cuenta que eso no funciona y proponiendo una alternativa, en caso de que funcione se dejará como esta o podemos llegar a otra opción lo que decidamos.
Gracias.

**Comment by JavierBravoDonaire** [comment]
He estado estudiando los códigos y he encontrado varios errores:
A parte de lo mencionado antes, la clase peliculas.java no añade 500 porque se ha puesto el if delante que el commit, por lo que hay solo 499, pero además, en el de actores el if es hasta 501 y entonces si mete los 500. (Se que los 500 es provisional pero para no cagarla más).
En las lineas siguientes:
result += "id = " + rs.getString("id") + "\n";
System.out.println("id = "+rs.getString("id") + "\n");
Deberia ser: rs.getString("id_pelicula") ya que es así como se ha llamado en las tablas.
Por último, se deberían suprimir las lineas que escriben en el terminal, ya que se ven en la propia página. Y mejorar los comentarios, ya que en los tres programas son iguales.
Mañana me pongo con ello y intentaré solucionar algunos de estos problemas.

**Comment by JavierBravoDonaire** [comment]
He estado estudiando los códigos y he encontrado varios errores:
A parte de lo mencionado antes, la clase peliculas.java no añade 500 porque se ha puesto el if delante que el commit, por lo que hay solo 499, pero además, en el de actores el if es hasta 501 y entonces si mete los 500. (Se que los 500 es provisional pero para no liarla más).
En las lineas siguientes:
result += "id = " + rs.getString("id") + "\n";
System.out.println("id = "+rs.getString("id") + "\n");
Deberia ser: rs.getString("id_pelicula") ya que es así como se ha llamado en las tablas.
Por último, se deberían suprimir las lineas que escriben en el terminal, ya que se ven en la propia página. Y mejorar los comentarios, ya que en los tres programas son iguales.
Mañana me pongo con ello e intentaré solucionar algunos de estos problemas.

**Comment by DanielRiveraPaniagua** [comment]
Problema abordado con la funcionalidad inicial
