### ISSUE TITLE
Datos limpios no son correctos y los datos que coge jdbc tampoco

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#44]
Según lo comentado por @JavierBravoDonaire en su issue #43 y tras estudiar el código de los jdbc junta a él. No creo que los datos limpios estén colocados de manera adecuada ni sirvan. 

Para empezar buscando un actor cualquiera, por ejemplo, Brad Pitt, puedes encontar que los únicos dos números que aparecen al lado,(suponiendo que son el id de la pélicula y el id del actor, por como lo trabajan las clases jdbc), te das cuenta que los dos números son diferentes en cada entrada, es decir, brad pitt tiene 72 ids diferentes.

Segundo problema, si es los datos de los actores, no debería aparecer los ids de las películas, por eso en nuestro esquema de la base de datos hay una tabla, "trabajan" que relaciona ambos ids de películas y actores. Puesto que los jdbc deberán tener una clase para cada tabla, sería mejor tener un archivo con los datos, para cada tabla.

El martes le dedicaré tiempo a separar los datos de cada tabla y los subiré al proyecto. Si creéis que algo de lo comentado aquí no es correcto, por favor decirlo.

**Comment by Noozh** [comment]
Segun la documentacion que se hizo cuando se mergearon los datos limpios el fichero con actores tiene este formato : 
{Apellido},{Nombre},{idpelicula}
Por tanto es normal que un actor tenga varias entradas (una por cada pelicula en la que trabaja).
Para utilizar ese fichero como fuente para rellenar la tabla de actores habria que quitar la columna de los ids y hacer un sort|unique de las columnas apellido y nombre.
Que los datos esten limpios no significa que puedan utilizarse todos ellos directamente para rellenar las tablas sin darles el formato adecuado que requiera cada tabla, simplemente implica que se han separado del fichero de partida de modo que resultan mas claros.

**Comment by DanielRiveraPaniagua** [comment]
Pues entonces queda hacer datos usables ya que los necesitamos para los jdbc. Sobretodo es por el zip de datos_actores que se se pidió para usar con ellas y que contiene un formato inadecuado para lo que se quiere utilizar por la repetición de los id de actores.

De paso intentar ordenar toda la información ya de manera adecuada en general para que procesarla sea generalmente más fácil uniendo toda la información que tenemos disponible, etc. 

Otra cosa que nos dimos cuentas es que el título de las películas quedó completamente unido y creemos que puede ser difícil de devolver a los clientes la información así, buscaremos una manera de separarlos o volverlos a procesar.

**Comment by ismagt** [comment]
Vale, me pongo con ello

**Comment by DanielRiveraPaniagua** [comment]
Tema siendo trabajado actualmente
