### ISSUE TITLE
Datos limpios de películas (Pull Request #48)

### ISSUE THREAD

**Issue by jaime0907** [DanielRiveraPaniagua/ProyectoFinal_ISI#49]
En el Pull Request #48 he subido un archivo txt separado por tabuladores donde están las películas que aparecen en ambos ficheros de datos (los del cliente y los de IMDb).
Algunos de los compañeros que están trabajando en esta parte del proyecto hemos estado hablando acerca de este asunto hoy en clase, pero me gustaría decirlo por aquí para que todos se puedan enterar:
Hemos llegado a la conclusión de que lo mejor es trabajar sobre estos datos que acabo de subir. Si el número de películas (que ahora queda reducido a 197.000) sigue siendo excesivo, en un futuro se ordenarían dichas películas por número de votos (usando la tabla rankings), y seleccionar las N primeras películas, dónde N sea un número que decidamos más adelante. No obstante, esto se podrá discutir más adelante.
Hay otra cosa importante a discutir: Los datos de este archivo no corresponde a ninguna de las tablas, es solo un auxiliar para poder relacionar las películas de IMDb con las del cliente
Para avanzar en el tema tablas propongo:

- Que se usen los datos de peliculas de IMDB como tabla "Películas" (el title.basics de los datos de IMDb, que habría que limpiar, recortar para sólo dejar las que aparezcan en mi archivo de películas, y dejar sólo los argumentos que hayamos especificado en el diagrama ER, recomiendo separar los campos por tabuladores para seguir una consistencia en todos los datos)

- Que el id para identificar películas a lo largo de toda la aplicación sea el de IMDb

Por otra parte, queda relacionar los datos de actores del cliente con los de IMDb. Para esto propongo:

- Crear un archivo de texto similar al actores.txt que hay subido en la carpeta datosLimpios, pero substituyendo el nombre y apellidos del actor por su id de IMDb (recomiendo simplemente buscar su nombre y apellido en la tabla de IMDb (name.basics) y quedarse con el primer resultado, en caso de haber varios), y el id de pelicula por el id de IMDb (usando el archivo que acabo de subir, que relaciona ambos ids). Este archivo sería la tabla relación actores-películas.

- Limpiar los datos de la tabla name.basics de IMDb, que es la que contiene los datos personales de los actores (tabla "Actores"). Esta tabla contiene muchos datos, por lo que recomiendo quedarse sólo con los que aparecan en los datos del cliente, algo similar a lo que he hecho con las películas.

Espero vuestras opiniones, pero vamos, es más o menos lo hablado en clase.

**Comment by oscarescuderoarnanz** [comment]
Estoy de acuerdo con lo comentado.

**Comment by DanielRiveraPaniagua** [comment]
Me parece perfecto.
 
Lo único que consideraría es, que para buscar los actores se puede emplear la tabla title.principals que relaciona el id de las películas con el id de los actores para asegurarnos de que el actor al que le estamos añadiendo la información sea el mismo. Si hay alguno que no podemos determinar a través de esa forma, entonces sí, añadir el primero que localizamos. Aprovechamos así también la información que ya teníamos que relacionaba cada actor y películas de la tabla de pedro.

En cuanto tengáis el de películas listo, agradeceríamos que se subiera para poder utilizarlo también en el ejemplo que estamos preparando. No corre prisa.

**Comment by DanielRiveraPaniagua** [comment]
Tema ya finalizado
