### ISSUE TITLE
Problemas de formato IMDB

### ISSUE THREAD

**Issue by ismagt** [DanielRiveraPaniagua/ProyectoFinal_ISI#50]
Intentando relacionar los datos iniciales del proyecto con lo de IMDB, nos han surgido algunas dudas y problemas.

-(grupo 6) En un principio la implementación de la tabla de Actores, implementamos un atributo País de Origen, pero en la información de IMDB(ficheros tsv),no viene, ¿qué proponéis?

-(grupo 3)Relacionado con IMDb también, para sacar los nombres de directores y guionistas IMDB te da nombre y apellidos juntos, y en el diagrama lo diferenciamos en nombre y apellidos, ¿con qué nos quedamos, junto o por separado?
- Con respecto a la tabla Peliculas, tengo anotado que un principio dentro de la tabla de Películas había un atributo Rating. Si queréis poner una tabla calificaciones que contenga Id_Pelicula y calificación, habría que hablarlo, ya que crear una tabla para dos atributos (aunque la información funcional es Rating). En IMDB además nos da el numero de votos en cada película por si lo queréis añadir a la base de datos.

**Comment by DanielRiveraPaniagua** [comment]
* Evidentemente si no tenemos esa información no la podemos incluir. Asi que yo diría de quitar lo de los países.
* Probablemente separar el nombre y apellido, a menos que vengan divididos de alguna forma concreta (apellidos, nombre por ejemplo) va a ser complicado, así que, si no se puede dividir esa información, la dejaría junta.
* No creo entender la última cuestión. 
    * En el diagrama la tabla películas tiene el rating, pero en los ajustes de la tabla que vienen debajo ya se habló de que el atributo rating sería bueno acompañarlo del número de votos (lo que también puede ayudarnos a determinar la popularidad de una película).
    * Calificación sin embargo, es todo lo de los grupos de edades a los que apela una película. En #16 ya se habló de, que de momento, trabajásemos solo con separación entre películas de adulto o no. A pesar de ser una tabla de dos atributos y, funcionalmete, 2 campos, creo que debería estar, porque la idea principal es, en algún momento, poder incluir en ella todos los códigos (por ejemplo en los datos de pedro había algunas películas calificadas)

**Comment by ismagt** [comment]
De acuerdo, pues los dos primeros puntos aclarados.
El último punto, mis disculpas, porque he confundido Calificaciones(rango de edades), con Rating(puntuación de una película). Aún así para dejar claro:
-Rating en una tabla aparte con 3 atributos: id_pelicula, rating, num_votos.
-Calificación(rango de edad), yo propongo directamente ponerlo como atributo en películas, es más y que fuera un boolean (SI o NO), siendo esta de adultos o no.

**Comment by DanielRiveraPaniagua** [comment]
* El rating en una tabla a parte si que no lo veo, porque es un atributo propio de cada película igual que el número de votos. En mi opinión puesto que es una característica intrínseca de cada una, lo dejaría en la misma tabla. No puedes sacarlo "en común" para todas las tablas.
* Sin embargo, y por la misma razón, y esto con más seguridad diciendo que cumpliríamos con lo de la 3ª forma normal de las bases de datos, si es adulta o no debería ir a parte, por que es como un sistema de calificación independiente de la película. Más que nada, si tenemos más atributos, en caso de cambiar el nombre de uno de ellos, puesto que el id no se vería afectado, no tendríamos que cambiar cada una de las filas donde aparece el nombre individualmente, si no solamente el nombre en su propia entidad. Es difícil de explicar XD. 

La forma correcta estoy bastante convencido que sería la que acabo de mencionar, pero depende un poco también de la implementación, sobretodo el segundo caso. ¿Qué opináis?

**Comment by jaime0907** [comment]
Cada película tiene una valoración media (rating), un número de votos y una clasificación (es adulta o no). Pienso que debería ir todo como atributos dentro de la tabla Películas. Haría más sencilla tanto la elaboración de tablas como las futuras queries para acceder a los datos.
En mi opinión, cuantas menos tablas tengamos, mejor.

**Comment by oscarescuderoarnanz** [comment]
Relacionado con el nombre y apellido, IMDb te lo da de forma junta. Es complejo separarlo, pues hay nombres compuestos, nombres con -,etc, por tanto, pienso que es mejor usar directamente el campo primaryName de IMDb el cual te da junto nombre + apellido.

**Comment by DanielRiveraPaniagua** [comment]
> Cada película tiene una valoración media (rating), un número de votos y una clasificación (es adulta o no). Pienso que debería ir todo como atributos dentro de la tabla Películas. Haría más sencilla tanto la elaboración de tablas como las futuras queries para acceder a los datos.
> En mi opinión, cuantas menos tablas tengamos, mejor.

Tenerlo todo como atributos, incluido la calificación, me parece una buena opción. Sobretodo por lo mencionado de simplificación y que de momento solo separamos adultas o no. Y lo demás tiene que estar en la tabla Películas de todas todas, totalmente de acuerdo. El número de tablas debe ser el correcto sin embargo. Esto nos lo comentó pedro ya, no ahorrar tablas por falta de espacio u otras razones. Pero vamos, el justo y necesario para una correcta distribución y diagrama, ni más ni menos, que es como lo estamos haciendo.

> Relacionado con el nombre y apellido, IMDb te lo da de forma junta. Es complejo separarlo, pues hay nombres compuestos, nombres con -,etc, por tanto, pienso que es mejor usar directamente el campo primaryName de IMDb el cual te da junto nombre + apellido.

Si no veis que se puedan separar no lo podeis hacer evidentemente. Lo decía porque de vez en cuando te ponen el apellido separado del nombre por una coma. Pero puesto que, como mencionas, no hay manera, pues listo, jajajaja. 

Creo que una buena tarea, una vez que esté todo colocado, sería rehacer el diagrama. Para subir imágenes, la wiki básicamente es un repo github con una carpeta que abrí llamada "resources". Si le dais a edit en la página del diagrama veis como usar las imágenes que introduzcáis.

**Comment by DanielRiveraPaniagua** [comment]
Tema ya finalizado
