### ISSUE TITLE
¿En que rama subimos los datos limpios?

### ISSUE THREAD

**Issue by oscarescuderoarnanz** [DanielRiveraPaniagua/ProyectoFinal_ISI#52]
¿A que rama realizamos el pull request de los datos limpios?
Entiendo que la master tiene todo lo anterior del proyecto, y estos datos limpios son los definitivos. ¿Creamos una rama solo para los datos?

**Comment by DanielRiveraPaniagua** [comment]
Hice una rama llamada buckup que tiene precisamente una copia de todo lo que teníamos previamente. Haced lo que creáis conveniente, la verdad es que no estoy seguro de si es mejor hacer una rama o  subirlo a la master.

Hemos perdido un poco el flujo al trabajar en partes separadas, así que a lo mejor subirlo a la master no es una mala idea, así nosotros podemos recuperarla y volver a unir el trabajo.
