### ISSUE TITLE
Posibles conflictos con los pull request

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#55]
Llevamos todos muchos días trabajando en nuestras ramas sin subir nada a la principal y cada uno por nuestros propios caminos, así que habrá problemas de merge seguro.

Para intentar solventarlos, dejad claro aquí qué archivos son los que se tienen que mantener como están y no se deberían borrar ni modificar por el camino.

Por ejemplo **Carpeta DatosLimpios no debería borrarse**

**Comment by ismagt** [comment]
la otra carpeta "datosLimpios" con "d" en minúscula, se podría borrar. Y la de BBDD, simplemente están los scripts sh de trabajo, pero vamos lo importante son los txt (como tal no hace falta para el futuro y se puede borrar)

**Comment by victorbrobles** [comment]
Una pregunta, los datos finales para hacer las tablas en jdbc son todos los que están dentro de la carpeta DatosLimpios no?

**Comment by oscarescuderoarnanz** [comment]
Buenas @victorbrobles, exacto, los datos limpios para subir a jdbc son los que se encuentran en la carpeta DatosLimpios.

**Comment by victorbrobles** [comment]
Vale perfecto.

**Comment by dcabezas96** [comment]
Acabo de realizar un pull request en el que se ha borrado la carpeta BBDD y datosLimpios que no eran necesarios, dejando la carpeta DatosLimpios evitando así conflictos con los nombres de las carpetas. Si veis necesario borrar alguna carpeta más comentadlo.

**Comment by victorbrobles** [comment]
De todas formas dentro de esa carpeta hay varios ficheros de películas y no sé muy bien cual usar.

Me vendría bien que me dijerais cual uso y qué significa cada campo de cada película

**Comment by DanielRiveraPaniagua** [comment]
Conflictos resueltos
