### ISSUE TITLE
Cambios en las funcionalidades y organizar los equipos

### ISSUE THREAD

**Issue by ismagt** [DanielRiveraPaniagua/ProyectoFinal_ISI#57]
Muy buenas:

He estado viendo las funcionalidades, y una de ellas, la de los idiomas, al no extraer esa información, deberíamos eliminarla.
Aparte de esta otra funcionalidad relacionada con la anterior es "Según rango de duración introducido por el cliente, mostrar películas en ese rango de duración", pero al no tener la duración no podemos filtrar.

Con esto además, quiero proponer que hay varias funcionalidades de filtrado de películas como puede ser por: titulo,año de la película,actor,guionistas,director, género, rating, calificación...etc

Por último me gustaría saber como vamos a organizar los equipos para cada una de las funcionalidades implementadas, una vez estén definidas.

Antes de modificar la Wiki (además creo que no puedo), me gustaría comentarlo a ver que os parece.

**Comment by oscarescuderoarnanz** [comment]
Referente a lo comentado sobre esta funcionalidad:
   * Según rango de duración introducido por el cliente, mostrar películas en ese rango de duración
Actualmente en peliculas.txt no se dispone de esta información pero en IMDB si: 
![Captura](https://user-images.githubusercontent.com/47352810/70950237-4f715c80-2060-11ea-8772-7d6ac1a6851b.PNG)
Por tanto, cuando desarrollemos esta funcionalidad modificaremos peliculas.txt añadiendo la duración de estas para poder crearla.

**Comment by DanielRiveraPaniagua** [comment]
Si vais a incluirlo, mejor incluirlo ya, nosotros también lo habíamos contemplado.

**Comment by ismagt** [comment]
Correcto en IMDB, creo que tambien venia lo de los idiomas. Pero como no se ha incluido pues supuse, que no se filtraría. Vale pues incluyo yo el nuevo peliculas.txt y borro los demás. Además que añadiré en el README los parámetros de las columnas.

**Comment by oscarescuderoarnanz** [comment]
Tema resuelto, procedo a cerrar Issue.
