### ISSUE TITLE
ORGANIZACION PROYECTO

### ISSUE THREAD

**Issue by oscarescuderoarnanz** [DanielRiveraPaniagua/ProyectoFinal_ISI#59]
Creo que es necesario antes de comenzar con las funcionalidades dejar organizado el repositorio en una rama, pues aun no tengo claro que rama es la que se va a usar. Ademas, tenemos los datos limpios, ¿alguien se está encargando de subirlos a jdbc?. Aunque entiendo que es un lio, porque no tengo muy claro cual son las versiones finales de los datos, teniendo en cuenta por ejemplo que de películas hay como 3 ficheros. 
En el pull request que acabo de realizar #58 he subido una carpeta con lo que creo que ya son los datos finales para subir a jdbc (revisarlo por favor, puede ser que se me haya escapado algun fichero de datos ), entiendo que el resto de ficheros de  datos *.txt ya no son necesarios.

**Comment by DanielRiveraPaniagua** [comment]
De la organización, junto a la documentación del esquema que deberíamos a seguir y a un ejemplo de la implementación de todo el sistema, nos estamos Javi, Dani Arévalo y yo. Estamos terminando un par de cosas y decidiendo otras pocas. Intentaremos que todo esté subido éste domingo para poder empezar todo el resto.

Queremos documentarlo todo bien, y organizarlo de la forma más clara posible, por eso nos está llevando un poco más de tiempo.

Cuando lo subamos lo intentaré subir en una rama devel y en la rama master. Trabajaremos en la devel hasta que el sistema sea estable y la subamos a la master. Intentaremos también subirlo solo con los archivos justos y necesarios, quitando todas las redundancias y cosas que no sirven.

Sentimos estar tardando un poco más de lo debido, pero nuestra idea es que una vez que esto esté listo del todo, el resto de partes serán mucho más rápidas de hacer.  Por supuesto, una vez subido si tenéis otras ideas o cambios decidlo. Y estaremos a vuestra disposición para todas las dudas que puedan surgir.

Mientras, para ir avanzando, podéis ir trabajando en vuestra implementación también. Decidiendo que queris necesitáis, la api rest de vuestra parte, determinado formularios si fueran necesarios, etc. Luego adaptar el código a la nueva estructura será más sencillo.

**Comment by victorbrobles** [comment]
Nuestro grupo se está encargando de subir todos los ficheros limpios que hay de momento a jdbc. Teníamos pensado subirlo cuando esté el definitivo de películas y el de clasificación por edades.

**Comment by DanielRiveraPaniagua** [comment]
@oscarescuderoarnanz  queda que organizeis en DatosLimpios el resto de archivos que están sueltos, y aquellos archivos que van a ser usados para subirse (las 500 películas, con sus actores,géneros,etc)

Además repito la necesidad de subir un diagrama ya corregido con las cosas como las tenemos finalmente. El readme.txt que habéis subido en DatosLimpios/DatosProcesadosFinales está bien, pero tiene que estar también subida es información a la wiki (aprovechad y poner que tipo de variable es, porque creo recordar que el id de imdb es string, para que quede constancia). 

Y según pone en el readme, todavía queda en películas final añadir el número de votos y la puntuación (qué pasa con ésto finalmente?).

**Comment by angeisa97** [comment]
El grupo 1 nos ponemos con añadir a películas.txt de la carpeta DatosLimpios/DatosProcesadosFinales las columnas relacionadas con rating, nº de votos y bit de isAdult ya que serán necesarias para diversas funcionalidades que salen en la wiki

**Comment by DanielRiveraPaniagua** [comment]
Tema resuelto
