### ISSUE TITLE
Version Diagrama Final

### ISSUE THREAD

**Issue by oscarescuderoarnanz** [DanielRiveraPaniagua/ProyectoFinal_ISI#65]
Este sería el diagrama final con el que nos estaríamos moviendo:

![diagrama](https://user-images.githubusercontent.com/47352810/71487319-e4234980-281a-11ea-8ab5-6fa1dff9ec2b.jpeg)

Revisar que esté todo correcto, si hay algun fallo comentarlo.

**Comment by Noozh** [comment]
Yo lo veo bien salvo por que incluiria un atributo idGenero en la entidad genero

**Comment by DanielRiveraPaniagua** [comment]
Estoy de acuerdo con Dani

**Comment by ismagt** [comment]
Yo en actores, he añadido el id pelicula dentro de actores, luego no hace falta tener un relación (id_pelicula,id_actor), según he visto en guionistas y directores esta así. Y en la entidad Géneros, tiene dentro de la tabla solo el nombre de los géneros, luego podríamos implementarlo como comentaba Dani, o simplemente quedarnos con relacion_generos_peliculas.txt que tiene el genero y la pelicula a la que pertenece

**Comment by DanielRiveraPaniagua** [comment]
Es que sí necesitamos la relación, creo que hemos comentado ya muchas veces el por qué tenemos que seguir el esquema y programarlo como si fuera una base de datos real. Si lo tenis así cambiadlo.

Si hace falta más razones, para empezar, es por que pedro nos dijo que no escatimáramos ese tipo de cosas. Y porque en cualquier base de datos lo que tendrías sería una relación en esos puntos.

**Comment by DanielRiveraPaniagua** [comment]
> Yo en actores, he añadido el id pelicula dentro de actores, luego no hace falta tener un relación (id_pelicula,id_actor), según he visto en guionistas y directores esta así. Y en la entidad Géneros, tiene dentro de la tabla solo el nombre de los géneros, luego podríamos implementarlo como comentaba Dani, o simplemente quedarnos con relacion_generos_peliculas.txt que tiene el genero y la pelicula a la que pertenece

De hecho he estado viendo el último pull request de oscar y lo tienen puesto en relaciones las relaciones y entidades las entidades

**Comment by oscarescuderoarnanz** [comment]
@DanielRiveraPaniagua en cuanto al id_genero, fue una cosa que hablaron en clase y pusieron en la wiki que ponian el nombre como primary key y quitaban el id, por eso lo he dibujado de esa forma.
Yo la parte de guionistas,directores y generos tienen sus respectivas relaciones, las cuales sí veo necesarias.

**Comment by victorbrobles** [comment]
Nosotros hemos creado la base de datos tal cual está el diagrama subido por @oscarescuderoarnanz , sin id_genero. Lo único que en actores, guionistas y directores hemos separado nombre y apellido para que luego sea más sencillo trabajar con ello.

**Comment by DanielRiveraPaniagua** [comment]
Nombre y apellido al final es difícil separarlos por eso se encuentran juntos ahora

**Comment by DanielRiveraPaniagua** [comment]
Diagrama ya añadido a la wiki
