### ISSUE TITLE
Par de funcionalidades para el Grupo 2

### ISSUE THREAD

**Issue by jaime0907** [DanielRiveraPaniagua/ProyectoFinal_ISI#67]
El Grupo 2 vamos a hacer estas dos funcionalidades básicas, que no aparecían en la wiki (las añadiré en cuanto termine de escribir esta issue):
- Filtrar películas por título. He pensado que lo suyo sería que mostrase pelis cuyo título empezase por lo indicado, en lugar de tener que indicar el título exacto. Ejemplo: si filtras por "Harry Potter", debería devolver las 8 películas de la saga Harry Potter.
- Filtrar películas por año. Un filtrado que en realidad son dos: por año exacto (películas del 1997, por ejemplo), o por rango de años (películas del 1982 al 1987, por ejemplo).

Estas funcionalidades no creo que nos lleven más de un par de días, pero quería avisar antes para que nadie se ponga a hacer lo mismo a la vez :)

**Comment by dpoloa** [comment]
No veo mal las nuevas funcionalidades, sobre todo la primera.
