### ISSUE TITLE
Error a la hora de subir peliculas.txt

### ISSUE THREAD

**Issue by ismagt** [DanielRiveraPaniagua/ProyectoFinal_ISI#68]
Tal como esta implementado el PeliculasDAOimp, no se puede subir el peliculas.txt, lo he conseguido arreglar, simplemente es que no tenia el atributo de calificación de edad (ya que se estaba comentando su inclusión en peliculas en #16). Mi equipo esta realizando el filtrado por género y nos ha resultado un impedimento para probarlo, lo comento por si alguien le sale error de incompatibilidad de tipos string al subir peliculas.txt.

**Comment by DanielRiveraPaniagua** [comment]
Subid si podéis la solución al problema

**Comment by DanielRiveraPaniagua** [comment]
Por cierto, en el main que habéis subido a devel, se os ha pasado incluir el path a géneros, creo que se os ha borrado en algún merge. @Noozh

**Comment by ismagt** [comment]
Vale dentro de nuestra rama devel2, tenemos solucionado el problema, no queriamos seguir trabajando en la devel ya que todavia no esta aceptado el pull request.
Si tienes razón ayer nos dimos cuenta que varias cosas se borraron en el merge, en la rama devel2 ya esta arreglado.
Aún así gracias por avisar

**Comment by DanielRiveraPaniagua** [comment]
Problema solventado con #82
