### ISSUE TITLE
Funcionalidades Grupo 6

### ISSUE THREAD

**Issue by dcabezas96** [DanielRiveraPaniagua/ProyectoFinal_ISI#70]
El grupo 6 va a realizar las siguientes funcionalidades:
-Género mostrando el listado de posibles géneros que tenemos
-Peliculas por género donde se sacan las películas una vez indicado el género. 

A continuación añadiré las descripciones pertinentes en la wiki en el apartado de funcionalidades y api rest para comprobar el correcto funcionamiento y un mejor entendimiento.

**Comment by dpoloa** [comment]
Creo que esta issue ha quedado bastante resuelta. Cierro issue.
