### ISSUE TITLE
DATOS LIMPIOS ERRONEOS

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#74]
En actores.txt hay actores repetidos, cada actor tiene que ser único. No es un gran problema porque detecta que ya están en la tabla y los ignora, por eso es solo un bug.

**Comment by DanielRiveraPaniagua** [comment]
Procurad que la última linea no tenga una linea en blanco

**Comment by oscarescuderoarnanz** [comment]
Actores.txt y su respectiva relacion fue realizado por @ismagt.

**Comment by ismagt** [comment]
es cierto, ahora subo los txt sin actores repetidos

**Comment by DanielRiveraPaniagua** [comment]
Vi que había errores en las relaciones de peliculasguionistas y en guionistas. Yo echaría un vistazo a todos los de filmselect por si acaso no están bien asociados con películas todos los datos

**Comment by oscarescuderoarnanz** [comment]
Reviso los ficheros .txt y los subo actualizados junto a la funcionalidad que estoy realizando @DanielRiveraPaniagua.

**Comment by oscarescuderoarnanz** [comment]
Resuelto todos los ficheros txt.
