### ISSUE TITLE
Funcionalidad Grafos

### ISSUE THREAD

**Issue by AdrianRiao** [DanielRiveraPaniagua/ProyectoFinal_ISI#75]
Se ha añadido a la documentación del proyecto un documento que describe una funcionalidad de la aplicación utilizando las clases de grafos.

El código de la funcionalidad ya está realizado. Únicamente falta añadirlo a la aplicación. Abro este issue para que le echéis un vistazo,  y si os parece bien añadirlo a la aplicación.

Un saludo.

**Comment by dpoloa** [comment]
A mi me parece bien. Por curiosidad, ¿cual sería la API REST para esta funcionalidad?

**Comment by Noozh** [comment]
A mi me parecen bien las dos funcionalidades que se proponen en la documentación en lo que a grafos se refiere.
En cuanto a lo que pregunta @dpoloa sobre la API creo que lo adecuado, dado que son funcionalidades referentes a actores, seria que los endpoints estuviesen en /Actores/loquesea; o en su defecto también estaría bien crear una nueva rama que contuviese sendas funcionalidades tal como /Grafos/loquesea.
