### ISSUE TITLE
¿Que pull request #71 - #76 es util?

### ISSUE THREAD

**Issue by oscarescuderoarnanz** [DanielRiveraPaniagua/ProyectoFinal_ISI#80]
¿Cual es la diferencia entre los pull request indicados?
En caso de que alguno de los dos no fuese necesario pienso que sería adecuado cerrarlo.

**Comment by dcabezas96** [comment]
El pull resquest 71 se puede borrar, que ahora lo quito, hay que dejar el 76 que es la versión actualizada del 71 ya con mejoras.

**Comment by oscarescuderoarnanz** [comment]
@dcabezas96 gracias! He visto que lo has cerrado.
Issue resuelto, lo cierro.
