### ISSUE TITLE
Funcionalidades de los selectAll

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#81]
Quería comentaros una cosa que es evidente con el pull request #79.

En un principio lo había planteado de manera que el controller busca "actores" y modifica su comportamiento un poco para mostrar todas las películas de cierto actor. Ahora con lo de las duraciones y otras funcionalidades que irán surgiendo como filtrar por director, número de votos, etc es evidente que no podemos tener decenas de métodos para sacar las combinaciones de éstos filtros (peliculas de un actor de una duración > x por ejemplo). 

Se me ha ocurrido una solución que subiré más adelante (básicamente cada programa lo que añade es una "subclausula" a la query asi que en base a si tenemos esa parte o no, se añade o no, es solo una teoría que tengo informaré si se puede o no).

Pero me gustaría conocer la opinión de todos al respecto de que éste selectAll funcione así, como una lista que filtrar con las diferentes cosas.

**Comment by jaime0907** [comment]
Me parece bien, además de necesario para poder escalar la aplicación.

Imagino que el camino a seguir sería, en el PeliculasController, hacer que _output_ tomase primero el valor que devuelve GetAllPeliculas, GetAllPeliculasByActor, GetAllPeliculasByDirector o similares (aquellos que requieren de unir otras tablas, y que devuelven algo del tipo "select * from peliculas"), y después concatenar a _output_ las condiciones que devuelvan los métodos de filtrado (GetAllPeliculasByDuracion, y demás métodos que realmente son solo un "select * from peliculas where loquesea").

Para ello, estos métodos (GetAllPeliculasByDuracion y similares), deberán devolver solo la "subclausula" que mencionas (por ejemplo, "duracion > 75", en lugar de "select * from peliculas where duracion > 75").

Si el resto está de acuerdo, deberíamos establecer cuanto antes el formato de estas subclausulas, y hacer el esqueleto de PeliculasController (y del resto de controladores).

**Comment by DanielRiveraPaniagua** [comment]
Creo que hay una manera más sencilla, por qué así te ves obligado o a crear una vista o empezar a comparar los distintos output.

La solución más facil es, a mi entender, sobrecargar el método de selectAll con los distintos objetos que queremos pedir (actores,duración,...) que pueden incluso venir en un diccionario y en base a qué se encuentre el DAOImpl ejecutar una query más larga o más corta. Por ejemplo (cuando seleccionamos un actor):

* A la query básica "select * from peliculas as p ", si existe la clave actor dentro del diccionario, añades "join peliculasactores as pa .... where fullnombre LIKE %" + actor + "% "  

* Se puede expandir constantemente ya que son cosas que se ejecutan superpuestas (si ahora queremos también concretar un director solo tiene que añadirse los joins correspondientes.

* Creo que los where son lo último que debería entrar en la query pero eso no es un gran problema porque se pueden tener cadenas join(preparar la query) y cadenas where(seleccionar el resultado)

Ya digo que intentaré subir un ejemplo cuanto antes para que podáis verlo y opinar.

**Comment by DanielRiveraPaniagua** [comment]
Cerrado con pull request #82
