### ISSUE TITLE
Funcionalidad idioma de título de películas (Grupo 2)

### ISSUE THREAD

**Issue by jaime0907** [DanielRiveraPaniagua/ProyectoFinal_ISI#86]
Hace un tiempo propuse añadir la funcionalidad de mostrar el título de la película en el idioma que el usuario quiera, ya que IMDb nos ofrece esos datos. Cuando tuvimos todo aquel lío de cortar los datos de películas y quedarnos con las 500 mejores no se añadió la tabla de nombres de películas en distintos idiomas.
Propongo que mi grupo (grupo 2) haga esta tabla, y desarrolle la funcionalidad, que tan solo sería un filtrado más. Por ejemplo, /peliculas/selectAll?idioma=ES mostraría las películas con el nombre en español, y en caso de no tener nombre en español, el nombre por defecto.

**Comment by DanielRiveraPaniagua** [comment]
Implementada
