### ISSUE TITLE
Funcionalidad de información de película

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#88]
Estoy trabajando en una funcionalidad que muestra la información completa de una película con el siguiente formato:
http://develjavi.herokuapp.com/peliculas/info?titulo=Star%20Wars

Me gustaría saber que os parece y qué más cosas añadiríais a parte del género cuando esté disponible.

Por ejemplo pensaba hacer un formulario con ello también.

**Comment by JavierBravoDonaire** [comment]
Me parece genial. En cuanto a añadir, pues ya puestos se puede añadir la duración y demás parámetros que tenemos en los datos.

**Comment by dpoloa** [comment]
No me parece mal, era el último paso para que la app estuviera completa.

Los datos que puedes introducir solo pueden ser de los que disponemos en la app, porque si no debemos extraerlos de la propia web.

**Comment by jaime0907** [comment]
Me parece bien, y además propongo que el selectAll de películas tenga una posible tercera salida (además del HTML normal y el JSON) que sea la misma salida HTML pero con hipervínculos que enlacen a la página de información de cada película.

**Comment by jaime0907** [comment]
He estado probando vuestro heroku y no he sido capaz de acceder a la info de películas con carácteres raros (concretamente, Ocean's Eleven). No creo que sea problema vuestro, sino de que las URLs y los carácteres no alfanuméricos no se llevan bien. Creo que lo mejor sería que añadieseis una segunda manera de acceder a la info de las pelis, por id: /info?id=x.
Por otra parte, he hecho la salida HTML con hipervículos que menciono en el comentario anterior. Lo teneis en mi repo (https://github.com/jaime0907/ProyectoFinal_ISI/tree/selectAllConLinks), y en cuanto hagáis el pull request de esta funcionalidad compruebo que funciona y hago nuestro pull request. He hecho el hipervínculo con /info?titulo=x, pero si finalmente hacéis lo de la id, lo cambio sin problema.

**Comment by DanielRiveraPaniagua** [comment]
Si no funciona ahí tampoco funciona cuando seleccionamos el titulo en selectAll, voy a mirar que solución podemos realizar

**Comment by DanielRiveraPaniagua** [comment]
Por cierto lo del id lo podríamos hacer si fuera en algún sentido útil para el cliente. Puesto que el cliente no tiene el id, ni lo sabe, no es útil en ningún momento. No creo que sea una buena.

**Comment by DanielRiveraPaniagua** [comment]
Solución fácil para lo de los string con marcas como por ejemplo Ocean's Eleven es rodear al string a buscar de $$string$$. Ésto escapa los caracteres necesarios. Aplicaremos la solución a todas las partes de la aplicación donde pudiera ser necesaria.

**Comment by DanielRiveraPaniagua** [comment]
@jaime0907 vamos a meter la versión con ?id adicionalmente para que vuestra aplicación de las urls sea más sencilla y exacta, además pensándolo bien, si hubiese películas con el mismo título así, el cliente puede utilizar el id como método alternativo. Añadiré también lo de $$ a las funcionalidades donde puede haber caracteres necesarios, pero para que tengáis en cuenta que podéis hacerlo mediante ?id= directamente. 

La aplicación buscará por el campo id preferentemente, si no, por el título. Lo aplicaremos también a actores, guionistas y directores, por si queréis hacer también una página con redirecciones para ellos.

Muchas gracias por la sugerencia.

**Comment by jaime0907** [comment]
@DanielRiveraPaniagua Perfecto, actualizado mi repo (https://github.com/jaime0907/ProyectoFinal_ISI/tree/selectAllConLinks) con la nueva funcionalidad por id, me quedo a la espera de vuestro pull request para probar el nuevo HTML y fusionar todo.

**Comment by DanielRiveraPaniagua** [comment]
Funcionalidades añadidas pullrequest #109 y #111
