### ISSUE TITLE
Funcionalidades Finales

### ISSUE THREAD

**Issue by DanielRiveraPaniagua** [DanielRiveraPaniagua/ProyectoFinal_ISI#89]
Me gustaría que cada grupo, cuando vaya finalizando sus funcionalidades, añada una entrada nueva a la página de la wiki describiéndola un poco para tener las que son definitivas organizadas finalmente en una página de la wiki
https://github.com/DanielRiveraPaniagua/ProyectoFinal_ISI/wiki/Funcionalidades-Finales

**Comment by DanielRiveraPaniagua** [comment]
Las que propusimos no están borradas, solo cambié el nombre de la página para diferenciarlas
https://github.com/DanielRiveraPaniagua/ProyectoFinal_ISI/wiki/Funcionalidades-Propuestas

**Comment by dpoloa** [comment]
He modificado el índice de la página de la wiki para distinguir entre ambas. Modifico también la página de Funcionalidades Finales para añadir la funcionalidad del grupo 1.

**Comment by DanielRiveraPaniagua** [comment]
Todo recogido y listo
