### ISSUE TITLE
Funcionalidad de información de actores, guionistas y directores

### ISSUE THREAD

**Issue by dpoloa** [DanielRiveraPaniagua/ProyectoFinal_ISI#90]
En relación a la nueva issue #88 que ha subido @DanielRiveraPaniagua, creo que, para ampliar un poco toda la información de nuestra app, podemos hacer también una nueva funcionalidad que recopile los datos principales de los actores y todas las películas en las que ha participado. Es igual que el filtro de peliculas, pero añadiendo los datos personales del actor/director/guionista.

Lo dejo como propuesta. Si es aceptado, nuestro grupo (1) se encargará de ello.

**Comment by DanielRiveraPaniagua** [comment]
Estábamos pensando justo lo mismo mi grupo y yo añadiendo además funcionalidad de los grafos para ver que otros actores, guionistas y directores son cercanos al buscado.

Puesto que estoy terminando la funcionalidad ya de películas, el trabajo que nos costaría a mi grupo hacerlas dos cosas juntas va a ser menor además de añadir de paso lo otro directamente. Si no os importa nos gustaría terminarlo a nosotros ya que estamos con ello :).

**Comment by dpoloa** [comment]
Cierro entonces esta issue.
