### ISSUE TITLE
Funcionalidad filtrado por puntuacion

### ISSUE THREAD

**Issue by oscarescuderoarnanz** [DanielRiveraPaniagua/ProyectoFinal_ISI#97]
Hemos pensado una funcionalidad que nos permita filtrar las peliculas por la puntuación, ahora mismo en heroku no funcionaria de manera completa, ya que tenemos solo las 500 mas valoradas, pero en el caso de que se hiciese con el ficheoro de peliculas completo, seria bastante interesante.
La funcionalidad estaría en el end-point /peliculas/selectAll, y utilizariamos queries para filtrar por igual a esa puntuacion ?rating=x, filtrado por rango ?rating=5-8 , o con > y <.

**Comment by oscarescuderoarnanz** [comment]
Además hemos pensado añadir la posibilidad de mostrar la pelicula mejor valorada de un año dado de la siguiente forma:
peliculas/selectAll?mejorpelicula=año

posibilidad de mostrar la pelicula mejor valorada de un año dado de la siguiente forma:
peliculas/selectAll?peorpelicula=año

De esta forma podemos obtener cual ha sido la mejor/peor pelicula de ese año.

**Comment by DanielRiveraPaniagua** [comment]
Puesto que es LA mejor película de un año concreto, no tiene por qué ir a selectAll, puede ir a otra funcionalidad, de hecho se puede mezclar con la funcionalidad de la info de películas, y redirigir la entrada a ella o con un hipervínculo. ¿Qué opináis?

**Comment by oscarescuderoarnanz** [comment]
Hemos realizado el cambio, se puede ver el cambio en el pull request #100

**Comment by DanielRiveraPaniagua** [comment]
resuelto
